/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DATE_H_RPCGEN
#define _DATE_H_RPCGEN

#include <rpc/rpc.h>


#define getDate 0x31234567
#define getDateVersion 1
#define DATE 1
extern  char ** date_1();
extern int getdate_1_freeresult ();

#endif /* !_DATE_H_RPCGEN */
